In [5]:
# get version of any lib
import numpy as np
print(np.__version__)

1.26.4


In [6]:
# write a program to get help with add function in numpy
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [9]:
#write a numpy program to test if any of the elements of a given array are non zero
import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print(np.any(x))

Original array:
[1 2 3 4]
True


In [22]:
# Write a program to test element wise positive or negative infinity
import numpy as np
array = np.array([1,-2,np.inf,-np.inf,0,3.5])
print("Original array:")
print(array)
result_pos_inf = np.isposinf(array)
result_neg_inf = np.isneginf(array)
print('result_pos_inf is' , result_pos_inf)
print('result_neg_inf is' , result_neg_inf)

Original array:
[ 1.  -2.   inf -inf  0.   3.5]
result_pos_inf is [False False  True False False False]
result_neg_inf is [False False False  True False False]


In [16]:
#write a pyton program to test element wise for NaN (Not a number of a given array)
import numpy as np
array = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(array)
print("Test element-wise for NaN:")
print(np.isnan(array))

Original array
[ 1.  0. nan inf]
Test element-wise for NaN:
[False False  True False]


In [19]:
# Write a python program to create an array of integers from 30 to 70
import numpy as np
array = np.arange(30,71)
print(array)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [20]:
# Write a python program to create an array of even integers from 30 to 70
import numpy as np
array = np.arange(30,71,2)
print(array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [21]:
#Write a python program to create 3*3 identity matrix
import numpy as np
array = np.identity(3)
print(array)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
#Write a python program to perform addition , substraction , multiplication of two matrx
import numpy as np
array1 = np.array([1,3,5,7,5,4])
array2 = np.array([8,5,9,5,5,6])
add = np.add(array1,array2)
print(add)
sub = np.subtract(array1,array2)
print(sub)
mul = np.multiply(array1,array2)
print(mul)


[ 9  8 14 12 10 10]
[-7 -2 -4  2  0 -2]
[ 8 15 45 35 25 24]


In [42]:
#write a program to reverse 4*4 array
import numpy as np
array = np.arange(16).reshape(4, 4)
print('original Array')
print(array)
print('reversed Array')
print(array[::-1])

original Array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
reversed Array
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [41]:
#Write a python program to transpose given 4*4 matrix
import numpy as np
array = np.arange(16).reshape(4, 4)
print('original Array')
print(array)
print('Transposed Array')
print(np.transpose(array))

original Array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Transposed Array
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [46]:
#Write a python program to create a new array from a given array from swapping first and last , second and third column
import numpy as np
array = np.arange(16).reshape(4, 4)
print('original Array')
print(array)
array[:, [0, 3]] = array[:, [3, 0]]
print('swapping first and last column')
print(array)
array[:, [1, 2]] = array[:, [2, 1]]
print('swapping second and third column')
print(array)

original Array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
swapping first and last column
[[ 3  1  2  0]
 [ 7  5  6  4]
 [11  9 10  8]
 [15 13 14 12]]
swapping second and third column
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]
